### ISSUE TITLE
Breadcrumbs overlap with file tab

### ISSUE THREAD

**Issue by poly2it** [wroyca/vscode-rounded#2] opened 2023-05-07 12:08 UTC
![Screenshot from 2023-05-07 14-04-25](https://user-images.githubusercontent.com/84731064/236676384-9ddab3bf-cbfd-4db9-8d68-c8be5ac76837.png)
Breadcrumbs overlap with the open file tab. The margin is not consistent between the top and bottom to relative to the grey separator.

Using [libadwaita-vscode-theme](https://github.com/wroyca/libadwaita-vscode-theme) with [vscode-adwaita](https://github.com/piousdeer/vscode-adwaita), recommended settings for both modifications.

**Comment by wroyca** [comment] 2023-05-07 21:14
Thank you for raising an issue!

You're correct in noting that breadcrumbs are not supported by design. This is mainly because GNOME currently lacks a design specification for them (as far as I know). Furthermore, this theme is designed to align with "the default" GNOME look, where applications like GNOME Builder or GNOME Text Editor typically do not include breadcrumbs. At this time, I don't have any plans to prioritize working on it, but I would gladly accept a pull request if one is submitted -

**Comment by wroyca** [comment] 2023-05-10 23:22
Fixed with https://github.com/wroyca/libadwaita-vscode-theme/commit/0f11f7622f4552d314e47b8103972a4b4958afd9

**Closed as completed by wroyca** 2023-05-10 23:22 UTC
Labels: enhancement, good first issue

**Comment by poly2it** [comment] 2023-05-14 19:29
Thank you and good work with the fix! 
> This is mainly because GNOME currently lacks a design specification for them (as far as I know).

![Screenshot from 2023-05-14 21-26-20](https://github.com/wroyca/libadwaita-vscode-theme/assets/84731064/17843541-ecc6-4e0b-9f4b-c65b9d7ab04a)
What about these breadcrumbs from GNOME files?

**Comment by wroyca** [comment] 2023-05-14 20:37
> Thank you and good work with the fix!
> 
> > This is mainly because GNOME currently lacks a design specification for them (as far as I know).
> 
> ![Screenshot from 2023-05-14 21-26-20](https://user-images.githubusercontent.com/84731064/238205928-17843541-ecc6-4e0b-9f4b-c65b9d7ab04a.png) What about these breadcrumbs from GNOME files?

Oh, that's intriguing! While I don't personally use breadcrumbs myself, I'm open to the idea and would gladly leave it to someone else who is interested in implementing it. Feel free to open a feature request! :)
